WARNING 2022-10-10 13:48:03,002 django.request.log_response:224- Not Found: /swagger/
WARNING 2022-10-10 13:48:03,004 django.server.log_message:161- "GET /swagger/ HTTP/1.1" 404 2911
WARNING 2022-10-10 13:48:03,582 django.request.log_response:224- Not Found: /favicon.ico
WARNING 2022-10-10 13:48:03,583 django.server.log_message:161- "GET /favicon.ico HTTP/1.1" 404 2920
ERROR 2022-10-10 13:48:12,189 django.request.log_response:224- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '-question' from 'form.captcha-question'
ERROR 2022-10-10 13:48:12,200 django.server.log_message:161- "GET / HTTP/1.1" 500 153816
ERROR 2022-10-10 13:55:48,397 django.request.log_response:224- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: simplemathcaptcha/captcha.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 994, in render
    return render_value_in_context(output, context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 973, in render_value_in_context
    value = str(value)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\utils\html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\boundfield.py", line 93, in as_widget
    return widget.render(
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\simplemathcaptcha\widgets.py", line 43, in render
    return super(MathCaptchaWidget, self).render(name, value, attrs=attrs, renderer=renderer)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\widgets.py", line 247, in render
    return self._render(self.template_name, context, renderer)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\widgets.py", line 252, in _render
    return mark_safe(renderer.render(template_name, context))
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\renderers.py", line 24, in render
    template = self.get_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\renderers.py", line 30, in get_template
    return self.engine.get_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simplemathcaptcha/captcha.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simplemathcaptcha/captcha.html
ERROR 2022-10-10 13:55:48,414 django.server.log_message:161- "GET / HTTP/1.1" 500 191551
WARNING 2022-10-10 13:55:49,040 django.request.log_response:224- Not Found: /favicon.ico
WARNING 2022-10-10 13:55:49,042 django.server.log_message:161- "GET /favicon.ico HTTP/1.1" 404 2920
ERROR 2022-10-10 13:57:12,530 django.request.log_response:224- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: simplemathcaptcha/captcha.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 994, in render
    return render_value_in_context(output, context)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\base.py", line 973, in render_value_in_context
    value = str(value)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\utils\html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\boundfield.py", line 93, in as_widget
    return widget.render(
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\simplemathcaptcha\widgets.py", line 43, in render
    return super(MathCaptchaWidget, self).render(name, value, attrs=attrs, renderer=renderer)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\widgets.py", line 247, in render
    return self._render(self.template_name, context, renderer)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\widgets.py", line 252, in _render
    return mark_safe(renderer.render(template_name, context))
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\renderers.py", line 24, in render
    template = self.get_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\forms\renderers.py", line 30, in get_template
    return self.engine.get_template(template_name)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simplemathcaptcha/captcha.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\saleh\Documents\GitHub\Portfolio\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simplemathcaptcha/captcha.html
ERROR 2022-10-10 13:57:12,569 django.server.log_message:161- "GET / HTTP/1.1" 500 191693
WARNING 2022-10-10 14:12:10,659 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:12:10,879 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:27:16,017 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:27:16,155 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:30:47,451 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:30:47,598 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:32:59,035 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:32:59,263 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:35:00,464 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:35:00,784 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:53:42,971 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:53:42,973 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:55:36,314 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:55:36,580 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 14:55:58,852 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 14:55:59,246 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 15:03:54,434 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 15:03:54,436 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 15:15:23,647 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 15:15:23,802 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 15:18:18,749 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 15:18:18,943 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 15:46:47,835 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 15:46:48,027 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 15:47:27,240 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 15:47:27,568 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 15:47:47,631 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 15:47:47,925 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:01:16,613 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:01:16,814 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:02:39,704 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:02:39,952 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:04:08,639 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:04:08,928 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:15:13,600 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:15:13,798 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:15:20,840 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:15:38,286 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:15:39,056 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:15:49,115 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:15:49,373 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:20:44,589 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:20:45,030 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:21:49,074 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:21:49,672 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:24:35,216 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:24:35,457 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 16:27:28,874 django.server.log_message:161- "GET /static/vendor/purecounter/purecounter.js.map HTTP/1.1" 404 1971
WARNING 2022-10-10 16:27:29,175 django.server.log_message:161- "GET /static/vendor/swiper/swiper-bundle.min.js.map HTTP/1.1" 404 1974
WARNING 2022-10-10 17:05:47,867 django.request.log_response:224- Not Found: /favicon.ico
WARNING 2022-10-10 17:05:47,868 django.server.log_message:161- "GET /favicon.ico HTTP/1.1" 404 2920
